### ISSUE TITLE
3.8 crashes with Emerald BPEE

### ISSUE THREAD

**Issue by roukaour** [Gamer2020/PokemonGameEditor#62]
I'm using an unmodified "1986 - Pokemon Emerald (U)(TrashMan).gba" ROM (SHA1 F3AE088181BF583E55DAF962A92BB46F4F1D07B7). I've tried the PGE 3.8 release and the beta Debug exe. Both of them crash with various tools.

The Trainer Editor:

    System.FormatException: Input string was not in a correct format.
       at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
       at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
       at PokemonGameEditor.TrainerEditor.ClassComboBox_SelectedIndexChanged(Object sender, EventArgs e)
       at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
       at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
       at PokemonGameEditor.TrainerEditor.TrainerListComboBox_SelectedIndexChanged(Object sender, EventArgs e)
       at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
       at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
       at PokemonGameEditor.TrainerEditor.TrainerEditor_Load(Object sender, EventArgs e)
       at System.Windows.Forms.Form.OnLoad(EventArgs e)
       at System.Windows.Forms.Form.OnCreateControl()
       at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
       at System.Windows.Forms.Control.CreateControl()
       at System.Windows.Forms.Control.WmShowWindow(Message& m)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.Form.WmShowWindow(Message& m)
       at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

The Pokémon Editor:

    System.ArgumentOutOfRangeException: InvalidArgument=Value of '65535' is not valid for 'SelectedIndex'.
    Parameter name: SelectedIndex
       at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
       at PokemonGameEditor.Pokemonedit.Baseload()
       at PokemonGameEditor.Pokemonedit.PKMNames_SelectedIndexChanged(Object sender, EventArgs e)
       at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
       at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
       at PokemonGameEditor.Pokemonedit.Pokemonedit_Load(Object sender, EventArgs e)
       at System.Windows.Forms.Form.OnLoad(EventArgs e)
       at System.Windows.Forms.Form.OnCreateControl()
       at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
       at System.Windows.Forms.Control.CreateControl()
       at System.Windows.Forms.Control.WmShowWindow(Message& m)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.Form.WmShowWindow(Message& m)
       at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I don't see any closed issues explaining how to solve this, either. Is it a known problem, or am I doing something wrong?

**Comment by roukaour** [comment]
Moving the ROM and the EXE into the same folder solved the problem.

**Comment by Gamer2020** [comment]
Closed as per our conversation.
